# Generated by Django 3.0.5 on 2020-05-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_accepted_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='accepted_terms',
        ),
    ]
