# Generated by Django 3.0.5 on 2020-05-16 01:51

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200515_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='images/default_avatar.jpg', null=True, upload_to=accounts.utils.upload_image_path),
        ),
    ]
