# Generated by Django 3.0.5 on 2020-05-22 20:32

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200515_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.utils.upload_image_path),
        ),
    ]
